# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4a4975cb0aaad4b630dd95a6e54d33b3d1f60c767702e5a4619e53559aa8075fc20ac4e87bcfc22fb51acd511ca9db2fe5f425719f16554ff09e59ddb0bff115

test:
  secret_key_base: da16fa84ec326fe2c6a0987316882c1efa02c1753c7b3ef56e1bcc59f937609f1b396d2a92f8c66e7d76ec93f7ddd3f41bffb6bc11e1b888628013bccb926a5a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
